name: qbittorrent

services:
  qbittorrent:
    container_name: ${QBITTORRENT_CONTAINER_NAME}
    image: qbittorrentofficial/qbittorrent-nox:${QBITTORRENT_VERSION}
    restart: unless-stopped
    env_file:
      - ./qbittorrent.env
    environment:
      - QBT_LEGAL_NOTICE=confirm
    ports:
      - 8080:8080
      - 52570:52570
      - 52570:52570/udp
    volumes:
      - ./config:/config
      - ./downloads:/downloads
