name: WireGuard Easy

networks:
  wg_easy_network:
    name: wg_easy_network

services:
  wg-easy:
    container_name: ${WG_EASY_CONTAINER_NAME}
    image: ghcr.io/wg-easy/wg-easy:${WG_EASY_VERSION}
    restart: unless-stopped
    environment:
      - INSECURE=true
    networks:
      # https://github.com/wg-easy/wg-easy/issues/2208#issuecomment-3398654919
      wg_easy_network:
        interface_name: eth0
        gw_priority: 1
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    volumes:
      - /lib/modules:/lib/modules:ro
      - ./config:/etc/wireguard
