services:
  minecraft-server:
    container_name: ${MINECRAFT_SERVER_CONTAINER_NAME}
    image: itzg/minecraft-server:${MINECRAFT_SERVER_VERSION}
    restart: unless-stopped
    env_file:
      - minecraft-server.env
    environment:
      - EULA=TRUE
    # Allow to run commands on the server with Docker `attach` command
    stdin_open: true
    tty: true
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
