services:
  glance:
    container_name: ${GLANCE_CONTAINER_NAME}
    image: glanceapp/glance:${GLANCE_VERSION}
    restart: unless-stopped
    env_file:
      - glance.env
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config:ro
